init:
  - git config --global core.autocrlf true

version: '{branch}-{build}'

image: Visual Studio 2017

skip_tags: true

configuration: Release
platform: Any CPU

shallow_clone: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: R2GPgreMublA7Xf82t4cap1J5soCnoi5eEtsTrvVXzPhtBV7RiMVBF973BDk+rFn

before_build:
- cmd: _build\restore.bat Configgy.NetFramework
    
build_script:
- cmd: _build\build.bat Configgy.NetFramework

test_script:
- cmd: _build\test.bat Configgy.NetFramework

after_test:
- cmd: _build\package.bat Configgy.NetFramework

artifacts:
- path: '*.nupkg'
  name: Nuget Package

deploy:
- provider: NuGet
  api_key:
    secure: P2oh37pn3l7Tp9qTP87aOB0GFxg8WnlFyV8n3p1eqMS5aUVur1Yg3xQ2inbIDOCr
  skip_symbols: false
  on:
    branch: master
